### ISSUE TITLE
Not working on Razer Blade 15 2020 advanced model

### ISSUE THREAD

**Issue by shiecldk** [datasone/grub-mod-setup_var#12]
Hi, this no longer works on the Intel 10 gen CPU Razer Blade model. I attach the bios file if you could help me look into it. Thank you. A related post is in here:
https://github.com/steelbrain/razer-blade-17-pro-2020-hackintosh/issues/3#issuecomment-730665995

Files:
dump (16 mb with ME+bios)
biosreg (12mb with bios only)
[dump.zip](https://github.com/datasone/grub-mod-setup_var/files/5571262/dump.zip)
[biosreg.zip](https://github.com/datasone/grub-mod-setup_var/files/5571261/biosreg.zip)

**Comment by datasone** [comment]
The "CFG Lock" settings in your firmware is stored in another varstore, you need to find the actual varstore the settings is in (here is varstore 0x11), and use the newly released `setup_var_cv` command to access it. You can read the new README for more info.
