### ISSUE TITLE
Enable XMP Profiles Dell Laptop

### ISSUE THREAD

**Issue by cheskyherskovic** [datasone/grub-mod-setup_var#14]
I don't know if this is a good place to post, I wanted to enable XMP 2.0 profiles on my XPS 17 so I tried the following but it was messed up and I was forced to reset the bios 
setup_var SaSetup 0x134 3
below is the file that I used to extract xmp values for
[Section_PE32_image_E6A7A1CE-5881-4B49-80BE-69C91811685C_Setup.sct.ifr.txt](https://github.com/datasone/grub-mod-setup_var/files/5752119/Section_PE32_image_E6A7A1CE-5881-4B49-80BE-69C91811685C_Setup.sct.ifr.txt)

**Comment by datasone** [comment]
You have used the commands wrongly, the old commands does not support custom variables, and it may interpreted the parameters wrong. I have made a new release with a command named `setup_var_cv` for varstores that is not named with "Setup". You can read the README about how to use it.
