### ISSUE TITLE
error:can't set variable using efi (error: 0x000000000000001a)

### ISSUE THREAD

**Issue by ghost** [datasone/grub-mod-setup_var#18]
主板是七彩虹cvn b460i frozen,解cfg锁发现数值已经是0x0，再次setup_var 0x3e 0x0就会提示error:can't set variable using efi (error: 0x000000000000001a) setup_var 0x3e 0x1也会error:can't set variable using efi (error: 0x000000000000001a)
设置什么值都这样
图片：
![yabb3q.jpg](https://s3.ax1x.com/2021/02/09/yabb3q.jpg)

**Comment by ghost** [comment]
无法设置的问题大概找到了 原因cfg lock不是设置在setup变量里的 是在CpuSetup里面的 能解才怪
就是不知道怎么让程序去CpuSetup里面设置
源代码也不是看的很懂[无奈][无奈]

**Comment by momoc-ani** [comment]
由于我缺少EFI工具开发相关的知识，
其实有一个新的思路：变量是存在某个guid位置上，我们可以写一个通用命令，通过guid 修改某个地址上的变量数值。。
比如：setup是在某个guid位置上的数据。guid是UUID，不存在重复的可能。
这个结论是我通过阅读这个工具部分源代码得出，不知道是否可行。
具体demo位置：
https://github.com/datasone/grub-mod-setup_var/blob/961a33cea8e169968ad10c7a8e2547d93a2117b5/grub-2.00%2B20130519/grub-core/efiemu/runtime/efiemu.c

![image](https://user-images.githubusercontent.com/31720689/107332801-99809180-6aef-11eb-9f6c-af78da033515.png)

**Comment by datasone** [comment]
新发了一个 release，加了 `setup_var_cv` 来处理这个情况，用的是 VarStore 的名称去选择 ~~（因为以前一直用的名称， GUID 还要加新的代码）~~

**Comment by ghost** [comment]
***你没写适用grub版本🤦‍♂️

**Comment by datasone** [comment]
> ***你没写适用grub版本🤦‍♂️

其实应该都能用，我去README里加一下🤦‍♂️

**Comment by ghost** [comment]
2.04之后要使用./bootstrap而不是./autogen.sh🤦‍♂️🤦‍♂️
