### ISSUE TITLE
问下能直接在普通的linux环境运行setup_var_3？

### ISSUE THREAD

**Issue by jinwyp** [datasone/grub-mod-setup_var#19]
能否把setup_var_3 命令复制出来？ 然后直接在debian 或 Ubuntu 运行吗？

这样就不需要弄启动盘了.  如果可以怎么能把setup_var_3 单独下载出来？

**Comment by datasone** [comment]
这个程序现在是重度依赖 grub 中提供的操作 EFI 变量的 API 的，如果想做成一个 Linux 下的程序的话相当于移植平台了，所以目前并不考虑这个。
