### ISSUE TITLE
Installation guide?

### ISSUE THREAD

**Issue by ghost** [datasone/grub-mod-setup_var#2]
I have reasonable question: what to do with these files?

**Comment by datasone** [comment]
Well, as said in the readme, this tool is intended to be used as a BIOS settings changer and only run when you need to. The usage guide link is outdated so I will update the readme to include relative information, you can also refer to [this](https://github.com/acidanthera/AppleSupportPkg#verifymsre2) for an example.

**Comment by truehomie** [comment]
@datasone thank you for response, I unlocked bios region using earlier version of Grub 
but I still unable to unlock IME FW region for reflashing cuz mine was probably corrupt during hard reset.
i get «Error 451 The host CPU does not have write access to….»

Should I unpack all the files into root folder? or there are more thing I should do?

**Comment by datasone** [comment]
Well, I don't think you can use this project to unlock the Descriptor Region as it may not be controlled by BIOS settings and differ widely between OEMs (e.g. For official ME firmware updates most laptops can update directly while Clevo laptops need to run a program first to reboot and unlock it, and some motherboards have a ME jumper locking this). So you should try to find the special way for your laptop/motherboard (maybe from modded BIOS) and then reflash.

P.S. Without success unlocking, Intel FPT (Flash Programming Tool) may help in some circumstances and SPI Programmer is the last resort as it directly writes into the BIOS chip and will not be limited by any other things.

**Comment by datasone** [comment]
Closed as no new responses.
