### ISSUE TITLE
[HIGH PRIORITY] Shasum of the files

### ISSUE THREAD

**Issue by dreamwhite** [datasone/grub-mod-setup_var#22]
Dear @datasone good morning,
thanks to a friend of mine I've noticed that you've released a new version of modGRUBShell.efi.
However I've noticed that the git commit signature isn't verified so I'm having a few doubts that the released version is the real one. Below a screenshot:

![image](https://user-images.githubusercontent.com/17933708/112289099-48d38b00-8c8e-11eb-85a7-3318c33c2aba.png)

Can you please fix your `git config --global user.name` and `git config --global user.email` values and provide me a SHA256 of the official file? 
Can I trust the release version?
Thanks and have a nice day
dreamwhite

**Comment by datasone** [comment]
Don't know how I configured the email to the username...
Anyway now the commit signatures should be OK, and the checksum of the binary file has been added to the release.

**Comment by dreamwhite** [comment]
> Don't know how I configured the email to the username...
> Anyway now the commit signatures should be OK, and the checksum of the binary file has been added to the release.

Thank you so much for fixing it and have a nice day
