### ISSUE TITLE
老大，改错了还能复原吗？

### ISSUE THREAD

**Issue by XobilePidor** [datasone/grub-mod-setup_var#32]
本人小白，顺着教程鼓捣黑果，但竟然没注意教程用的不是完全一样的型号，改完了才意识到var可能不一样……
改完系统还能正常启动，但是比原来卡了很多，经常假死，且发热严重，续航下降得也厉害。我试过直接重刷bios但并没有用。
求问老大两个问题：
一是重刷bios能恢复回去吗？
二是我ifrextract把官方bios包解开，搜我改掉的那两个var，但搜到好几个重名的，如果要把grub shell还原，我怎么确认我应该改哪个……我看的教程里cfg lock和超频分别是CpuSetup 0x3e和CpuSetup 0xda，但我搜我的bios，有好几个0x3e和0xda，要怎么确定哪个才是呢？
希望老大能看到并帮帮小弟，感谢了！

**Comment by datasone** [comment]
1. 重置 BIOS 设置、重刷（非官方更新）都有可能能重置，看具体 OEM 的实现
2. 较新版本的 `ifrextract` 结果中，变量在 `VarStoreInfo` 之后还会有 `VarStore: 0xXX`，这个值对应了结果文件头部 `VarStore` 列表里的相应 ID，那里会有对应的 `VarStore` 名称（e.g. `CpuSetup`）
