### ISSUE TITLE
华硕PRIME H410T2/CSM主板的aperture size值0x44 修改异常

### ISSUE THREAD

**Issue by canghaiwuhen** [datasone/grub-mod-setup_var#33]
想修改华硕PRIME H410T2/CSM主板的aperture size
UEFITool和IRFExtractor配合
可以搜到Aperture Size是0x44
用setup_var_3 0x44看到的值是0x0，和默认的0x1对不上

0x52CB6 			One Of: Aperture Size, VarStoreInfo (VarOffset/VarName): 0x44, VarStore: 0x16, QuestionId: 0x2755, Size: 1, Min: 0x0, Max 0xF, Step: 0x0 {05 91 2E 07 2F 07 55 27 16 00 44 00 14 10 00 0F 00}
0x52CC7 				One Of Option: 128MB, Value (8 bit): 0x0 {09 07 30 07 00 00 00}
0x52CCE 				One Of Option: 256MB, Value (8 bit): 0x1 (default) {09 07 31 07 30 00 01}
0x52CD5 				One Of Option: 512MB, Value (8 bit): 0x3 {09 07 32 07 00 00 03}
0x52CDC 				One Of Option: 1024MB, Value (8 bit): 0x7 {09 07 33 07 00 00 07}
0x52CE3 				One Of Option: 2048MB, Value (8 bit): 0xF {09 07 34 07 00 00 0F}
0x52CEA 			End One Of {29 02}

BIOS文件下载地址：https://dlcdnets.asus.com/pub/ASUS/mb/BIOS/PRIME-H410T2-CSM-SI-1620.ZIP

**Comment by datasone** [comment]
`VarStore: 0x16` 代表着（新版 IFR 提取出 txt 文件开头处的）对应的 `VarStoreId` 为 `0x16`，对应的 `VarStore` 的名称大概率不为默认访问的 `Setup`。所以需要找到相应的名称并使用 `setup_var_cv` 命令。

------

`VarStore: 0x16` represents a `VarStore` with `VarStoreId 0x16`, which is often not the default `Setup`. So it's required to find the corresponding name of `VarStore` (at the top of IFR extracted txt), and use the `setup_var_cv` command to access the variable.

**Comment by canghaiwuhen** [comment]
明白了 刚刚也看另一个issue 我试试 多谢

**Comment by canghaiwuhen** [comment]
搞定 非常感谢！！
