### ISSUE TITLE
I can't use setup_var

### ISSUE THREAD

**Issue by johnnynunez** [datasone/grub-mod-setup_var#4]
I have problems with change values
error: can't set variable using efi (error: 0x000000000000008)
![photo5780724199290156794](https://user-images.githubusercontent.com/22727137/78379538-ce1fe480-75d2-11ea-9568-70e327a157bb.jpg)
![photo5780724199290156796](https://user-images.githubusercontent.com/22727137/78379544-cf511180-75d2-11ea-9029-d699826535b1.jpg)
![photo5780724199290156795](https://user-images.githubusercontent.com/22727137/78379545-cfe9a800-75d2-11ea-9e4c-9d38c7da30b7.jpg)

**Comment by datasone** [comment]
The error 0x8 is GRUB_EFI_WRITE_PROTECTED, which is defined [here](https://github.com/datasone/grub-mod-setup_var/blob/3f15bf2f206f181c5a501f82cad7b3e0f370faa1/grub-2.00%2B20130519/include/grub/efi/api.h#L483).
If the computer is a laptop, it is most probable that the computer manufacture has locked the UEFI firmware thus preventing modifying variables. And it is usually very hard to bypass the limitations without support from the manufacture, which, in this circumstance, is rather unlikely.
Anyway, this error should be an issue related to the firmware.
