### ISSUE TITLE
Screen shot / text grab of the EFI shell output?

### ISSUE THREAD

**Issue by bibikalka1** [datasone/grub-mod-setup_var#42]
@datasone 

Is there any way to capture what's on the screen into a file, or redirect the EFI shell output to a file?

**Comment by datasone** [comment]
I don't think capturing is supported , but you should be able to redirect the output to file using `>` in a **v2** UEFI Shell

**Comment by bibikalka1** [comment]
> I don't think capturing is supported , but you should be able to redirect the output to file using `>` in a **v2** UEFI Shell

@datasone 

Actually, it seems everything is  mounted read-only, if I believe this:
https://superuser.com/questions/1713608/grub2-terminal-redirect-command-output-to-file
Since GRUB intentionally contains no code for writing to file systems, it can easily provide a guaranteed read-only mount mechanism.

But! I think that I can simply capture pictures of the command output with the phone, and do OCR on it.
