### ISSUE TITLE
Does not work on Dell Inspiron 7490

### ISSUE THREAD

**Issue by geeuk** [datasone/grub-mod-setup_var#6]
Hi, I am trying to run this efi file on Dell Inspiron 7490 i7-10510u. The issue is this dell does not have legacy rom option so only native uefi is the only option that can be used.

I am thinking this grub version does not support native uefi mode? Because when I try to load it, it just freezes on Dell logo. I disabled secure boot and also bitlocker..

Any suggestions please.

edit: i just run ubuntu 20.04 with Grub Version 2.04 and it worked flawlessly. Can I somehow rebuild your script to work with Grub2.04.

![20200418-160713](https://user-images.githubusercontent.com/63922415/79644345-41fbe880-81a0-11ea-9b1b-6eb3ee8b4801.jpg)

**Comment by datasone** [comment]
Though this project is based on grub, it's not a bootloader, so that the mod GRUB shell can only be started from a UEFI Shell environment. You should first boot a UEFI shell and then execute the mod GRUB Shell in it.
