### ISSUE TITLE
Z490 and identical offsets

### ISSUE THREAD

**Issue by BoringBoredom** [datasone/grub-mod-setup_var#9]
A lot of settings have the same offset on Z490 boards, e.g. on Apex:
0x1A: PEP I2C1 | High Precision Timer | HW Change Show Warning | CPU Core Voltage | Temperature Source 1 | 1 or more unknown settings
Is there a way to specify the VarStore when running the command?

**Comment by BoringBoredom** [comment]
> 0x5610C 	VarStore: VarStoreId: **_0x17_** [4570B7F1-ADE8-4943-8DC3-406472842384], Size: 0x6EC, Name: PchSetup {24 1F F1 B7 70 45 E8 AD 43 49 8D C3 40 64 72 84 23 84 17 00 EC 06 50 63 68 53 65 74 75 70 00}

> 0x6C285 				One Of: High Precision Timer, VarStoreInfo (VarOffset/VarName): **_0x1A_**, VarStore: **_0x17_**, QuestionId: 0x661, Size: 1, Min: 0x0, Max 0x1, Step: 0x0 {05 91 BF 0A C0 0A 61 06 17 00 1A 00 10 10 00 01 00}
0x6C296 					One Of Option: Disabled, Value (8 bit): **_0x0_** {09 07 04 00 00 00 00}
0x6C29D 					One Of Option: Enabled, Value (8 bit): **_0x1_** (default) {09 07 03 00 30 00 01}
0x6C2A4 				End One Of {29 02}

imo, a clean and safe way to do it would be
> setup_var VarStoreId VarOffset Value

read the current value:
> setup_var 0x17 0x1A

disable it:
> setup_var 0x17 0x1A 0x0

enable it:
> setup_var 0x17 0x1A 0x1

**Comment by datasone** [comment]
There is a modified version that can choose VarStore mentioned [here](https://github.com/datasone/grub-mod-setup_var/issues/5#issuecomment-612967491), it uses VarStore name to choose VarStore, and had been verified on VMWare UEFI firmware.

**Comment by datasone** [comment]
The name should be the name of the VarStore, which in your dump is `PchSetup`.
